type = "javascript"
name = "stock-auto-cloudflare-admin"
main = "src/index.js"
compatibility_date = "2026-03-02"
workers_dev = true
## 아래 환경별 설정 및 변수는 필요시 Cloudflare Dashboard에서 관리
## [env.production]
## route = "admin.yourdomain.com/*"
## zone_id = ""
## [env.staging]
## workers_dev = true
## [vars]
## BACKEND_BASE_URL = "https://stock-admin.loca.lt"
